// docgen generates docs/rules.md from the live rule registry.
// Run: go run ./hack/docgen > docs/rules.md
package main

import (
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/OWNER/triage/internal/findings"
	"github.com/OWNER/triage/internal/rules"

	// Import all rule packages to trigger init() registration.
	_ "github.com/OWNER/triage/internal/rules"
)

func main() {
	all := rules.All()

	// Group by category.
	byCategory := map[findings.Category][]findings.RuleMeta{}
	for _, r := range all {
		m := r.Meta()
		byCategory[m.Category] = append(byCategory[m.Category], m)
	}

	// Sort categories.
	cats := make([]string, 0, len(byCategory))
	for c := range byCategory {
		cats = append(cats, string(c))
	}
	sort.Strings(cats)

	w := os.Stdout

	fmt.Fprintln(w, "# triage — Diagnostic Rules")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "> This file is auto-generated by `go run ./hack/docgen`. Do not edit by hand.")
	fmt.Fprintln(w, "")
	fmt.Fprintf(w, "**%d rules** across %d categories.\n", len(all), len(cats))
	fmt.Fprintln(w, "")

	// Summary table.
	fmt.Fprintln(w, "## Summary")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "| Rule ID | Title | Severity | Confidence | Scopes |")
	fmt.Fprintln(w, "|---------|-------|----------|------------|--------|")

	sortedAll := make([]findings.RuleMeta, len(all))
	for i, r := range all {
		sortedAll[i] = r.Meta()
	}
	sort.Slice(sortedAll, func(i, j int) bool {
		return sortedAll[i].ID < sortedAll[j].ID
	})
	for _, m := range sortedAll {
		scopes := make([]string, len(m.Scopes))
		for i, s := range m.Scopes {
			scopes[i] = string(s)
		}
		fmt.Fprintf(w, "| [%s](#%s) | %s | %s | — | %s |\n",
			m.ID, anchor(m.ID), m.Title, m.Severity, strings.Join(scopes, ", "))
	}
	fmt.Fprintln(w, "")

	// Per-category sections.
	for _, cat := range cats {
		metas := byCategory[findings.Category(cat)]
		sort.Slice(metas, func(i, j int) bool { return metas[i].ID < metas[j].ID })

		fmt.Fprintf(w, "## %s\n\n", titleCase(cat))

		for _, m := range metas {
			fmt.Fprintf(w, "### %s\n\n", m.ID)
			fmt.Fprintf(w, "**%s**\n\n", m.Title)
			fmt.Fprintf(w, "- **Severity:** %s\n", m.Severity)
			scopes := make([]string, len(m.Scopes))
			for i, s := range m.Scopes {
				scopes[i] = string(s)
			}
			fmt.Fprintf(w, "- **Scopes:** %s\n", strings.Join(scopes, ", "))
			if len(m.DocsLinks) > 0 {
				fmt.Fprintf(w, "- **Docs:** %s\n", strings.Join(m.DocsLinks, ", "))
			}
			fmt.Fprintln(w, "")
			if m.Description != "" {
				fmt.Fprintln(w, m.Description)
				fmt.Fprintln(w, "")
			}
		}
	}
}

func anchor(id string) string {
	return strings.ToLower(strings.ReplaceAll(id, "-", "-"))
}

func titleCase(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}
